-- GIVE ALL PERMS TO MODEL RELATED TO SNOWFLAKE
DECLARE
  cursor c1 is
    SELECT table_name
    FROM all_tables
    WHERE owner = 'SNOWFLAKE';
BEGIN
  FOR r1 IN c1 LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON SNOWFLAKE.' || r1.table_name || ' TO DATAMODEL';
  END LOOP;
END;
/

-- GIVE ALL PERMS TO SNOWFLAKE RELATED TO MODEL
DECLARE
  cursor c1 is
    SELECT table_name
    FROM all_tables
    WHERE owner = 'DATAMODEL';
BEGIN
  FOR r1 IN c1 LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DATAMODEL.' || r1.table_name || ' TO SNOWFLAKE';
  END LOOP;
END;
/